AllCops:
  DisabledByDefault: false
  DisplayCopNames: true

Layout/IndentationWidth:
  Enabled: true
  Width: 4
  AllowAutodetection: true

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 100

Metrics/BlockLength:
  Max: 25